# App Properties
onuraltuntas:
  app:
    jwtSecret:
      secretKey
    jwtExpirationMs:
      86400000 # 1day
    jwtRefreshExpirationMs:
      2592000000 # 1month

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/spring_blog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


