# App Properties
onuraltuntas:
  app:
    jwtSecret:
      secretKey
    jwtExpirationMs:
      3600000
    jwtRefreshExpirationMs:
      86400000

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/spring_blog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


